# -*- coding: utf-8 -*-
"""ProgrammingDAAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYs_c04Z8x-nnCHTTyXKXq5DDQnwTZcU

Data Understanding
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

df = pd.read_excel('Sales Data_PDA_4052.xlsx')

df.head()

df.tail()

df.sample(5)

df.shape

df.columns

df = pd.read_excel("Sales Data_PDA_4052.xlsx", header=1)

df.columns

df.index

df.info()

df.dtypes

df.rename(columns={'value_£': 'sales_value'}, inplace=True)

df.columns

df.describe()

df['date'] = pd.to_datetime(df['date']).dt.normalize()

df.describe()

df.head()

df['date'].max()

print("Earliest date:", df['date'].min().date())
print("Latest date:", df['date'].max().date())

df.nunique()

df.isnull().sum()

df.notnull().sum()

df.duplicated().sum()

df['sales_person'].value_counts()

df['priority'].value_counts()

df['ship_mode'].value_counts()

"""Data Preparation"""

df_clean = df.copy()

df_clean.head()

df_clean.duplicated().sum()

df_clean.columns

df_clean.isnull().sum()

missing_total = df_clean.isnull().sum().sum()
missing_total

df_clean.notnull().sum()

df_clean.dtypes

df_clean = df_clean.convert_dtypes()

df_clean.dtypes

df_clean.info()

for col in df_clean.select_dtypes(include=['string']).columns:
    print("Column:", col)
    print(df_clean[col].value_counts(dropna=False))
    print("-" * 50)

for col in df_clean.select_dtypes(include=['string']).columns:
    df_clean[col] = df_clean[col].str.strip()

for col in df_clean.select_dtypes(include=['string']).columns:
    print("Column:", col)
    print(df_clean[col].value_counts(dropna=False))
    print("-" * 50)

df_clean['sales_value'].head(10)

"""Outlier Detection"""

df_clean.describe()

outlier_summary = {}

for col in df_clean.select_dtypes(include=np.number).columns:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    mask = (df_clean[col] < lower) | (df_clean[col] > upper)

    outlier_summary[col] = mask.sum()

outlier_summary

df_clean.select_dtypes(include=np.number).plot(
    kind='box',
    figsize=(10,5)
)

plt.title("Boxplot of Numerical Columns")
plt.show()

"""Data reduction"""

df_analysis = df_clean.copy()

df_analysis['year'] = df_analysis['date'].dt.year
df_analysis['month'] = df_analysis['date'].dt.month
df_analysis['day'] = df_analysis['date'].dt.day

df_analysis.head()

df_analysis.info()

df_analysis.describe()

"""Data Analysis"""

df_analysis['sales_value'].describe()

total_sales = df_analysis['sales_value'].sum()
average_sales = df_analysis['sales_value'].mean()
minimum_sales = df_analysis['sales_value'].min()
maximum_sales = df_analysis['sales_value'].max()

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Minimum Sales:", minimum_sales)
print("Maximum Sales:", maximum_sales)

total_orders = df_analysis['order_id'].count()
total_orders

# Total sales by salesperson
salesperson_total = df_analysis.groupby('sales_person')['sales_value'].sum()

salesperson_total

salesperson_average = df_analysis.groupby('sales_person')['sales_value'].mean()

salesperson_average

salesperson_orders = df_analysis.groupby('sales_person')['order_id'].count()

salesperson_orders

salesperson_total.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Total Sales by Salesperson")
plt.xlabel("Salesperson")
plt.ylabel("Total Sales")
plt.show()

# Total sales by priority
priority_total = df_analysis.groupby('priority')['sales_value'].sum()
priority_total

priority_average = df_analysis.groupby('priority')['sales_value'].mean()
priority_average

priority_orders = df_analysis.groupby('priority')['order_id'].count()
priority_orders

priority_total.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Total Sales by Priority")
plt.xlabel("Priority")
plt.ylabel("Total Sales")
plt.show()

priority_average = df_analysis.groupby('priority')['sales_value'].mean()
priority_average

df_analysis.boxplot(
    column='sales_value',
    by='priority',
    figsize=(10,6)
)

plt.title("Sales Value Distribution by Priority")
plt.suptitle("")
plt.xlabel("Priority")
plt.ylabel("Sales Value")
plt.show()

ship_total = df_analysis.groupby('ship_mode')['sales_value'].sum()
ship_total

ship_average = df_analysis.groupby('ship_mode')['sales_value'].mean()
ship_average

ship_orders = df_analysis.groupby('ship_mode')['order_id'].count()
ship_orders

ship_total.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Total Sales by Shipping Mode")
plt.xlabel("Shipping Mode")
plt.ylabel("Total Sales")
plt.show()

monthly_sales = df_analysis.groupby('month')['sales_value'].sum()
monthly_sales

monthly_orders = df_analysis.groupby('month')['order_id'].count()
monthly_orders

monthly_average = df_analysis.groupby('month')['sales_value'].mean()
monthly_average

monthly_sales.plot(
    kind='line',
    marker='o',
    figsize=(8,5)
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.show()

"""Data Visualisation"""

# Histogram of sales values
df_analysis['sales_value'].plot(
    kind='hist',
    bins=30,
    figsize=(8,5)
)

plt.title("Distribution of Sales Values")
plt.xlabel("Sales Value")
plt.ylabel("Frequency")
plt.show()

df_analysis.boxplot(
    column='sales_value',
    figsize=(8,5)
)

plt.title("Boxplot of Sales Values")
plt.ylabel("Sales Value")
plt.show()

plt.figure(figsize=(8,5))

plt.scatter(
    df_analysis['order_id'],
    df_analysis['sales_value']
)

plt.title("Sales Value by Order")
plt.xlabel("Order ID")
plt.ylabel("Sales Value")

plt.show()

ship_orders.plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(7,7)
)

plt.title("Order Distribution by Shipping Mode")
plt.ylabel("")

plt.show()

salesperson_total.plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(7,7)
)

plt.title("Sales Contribution by Salesperson")
plt.ylabel("")

plt.show()

monthly_orders.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Monthly Order Count")
plt.xlabel("Month")
plt.ylabel("Number of Orders")

plt.show()

import seaborn as sns

correlation_data = df_analysis[['sales_value', 'month']].corr()

plt.figure(figsize=(6,4))

sns.heatmap(
    correlation_data,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()

salesperson_total = df_analysis.groupby('sales_person')['sales_value'].sum()

salesperson_total.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Total Sales by Salesperson")
plt.xlabel("Salesperson")
plt.ylabel("Total Sales")
plt.show()

priority_total = df_analysis.groupby('priority')['sales_value'].sum()

priority_total.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Total Sales by Priority")
plt.xlabel("Priority")
plt.ylabel("Total Sales")
plt.show()

ship_total = df_analysis.groupby('ship_mode')['sales_value'].sum()

ship_total.plot(
    kind='bar',
    figsize=(8,5)
)

plt.title("Total Sales by Shipping Mode")
plt.xlabel("Shipping Mode")
plt.ylabel("Total Sales")
plt.show()

monthly_sales = df_analysis.groupby('month')['sales_value'].sum()

monthly_sales.plot(
    kind='line',
    marker='o',
    figsize=(8,5)
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.show()

df_analysis.boxplot(
    column='sales_value',
    by='priority',
    figsize=(10,6)
)

plt.title("Sales Value Distribution by Priority")
plt.suptitle("")
plt.xlabel("Priority")
plt.ylabel("Sales Value")
plt.show()

priority_mapping = {
    'Low': 1,
    'Medium': 2,
    'High': 3,
    'Critical': 4,
    'Not Specified': 0
}


df_analysis['priority_numeric'] = df_analysis['priority'].map(priority_mapping)


corr_data = df_analysis[['sales_value', 'priority_numeric']]

correlation_matrix = corr_data.corr()


import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap: Priority vs Sales Value")

plt.show()